// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type DeleteUser struct {
	ID string `json:"Id"`
}

type Link struct {
	ID      string `json:"Id"`
	Title   string `json:"title"`
	Address string `json:"address"`
	User    string `json:"user"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
	UserID  string `json:"user_id"`
}

type NewProfileImage struct {
	UserID string          `json:"userId"`
	File   *graphql.Upload `json:"file,omitempty"`
}

type NewUser struct {
	ID        string `json:"Id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Dob       string `json:"dob"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type ProfileImage struct {
	UserID string         `json:"userId"`
	File   graphql.Upload `json:"file"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type UpdateUser struct {
	ID        string `json:"Id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Dob       string `json:"dob"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type User struct {
	ID        string `json:"Id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Dob       string `json:"dob"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
